#!/usr/bin/env bash

SITES="reddit.com twitter.com facebook.com linkedin.com pinterest.com"

HOSTFILE="/etc/hosts"

if [ ! -w $HOSTFILE ]; then
    echo "Cannot write to $HOSTFILE, try running with sudo!"
    exit 1
fi

# Clean up previous entries from /etc/hosts
sed -i -e '/#gsd$/d' $HOSTFILE

# Write hosts file if 'work' mode
if [ "$1" != "--play" ]
then
    for SITE in $SITES; do
	    echo -e "127.0.0.1\t$SITE\t#gsd" >> $HOSTFILE
	    echo -e "127.0.0.1\twww.$SITE\t#gsd" >> $HOSTFILE
    done
    echo "Work mode enabled, run with --play to disable"
fi

if [ "$(uname -s)" == "Darwin" ]; then
	dscacheutil -flushcache
elif [ "$(uname -s)" == "Linux" ]; then
	for BROWSER in chromium firefox iceweasel; do
		killall $BROWSER > /dev/null 2>&1
	done
fi
