#!/bin/bash

# The outline of a quick and dirty way to check whether anything between specific HTML fields has changed.
# Run this scrip on a CRON scheduler and change the input of the cURL command and the sed command to customize.

date

name="HASC"
path="/Users/harrisoncramer/Checkers/sitesChecked"
oldfile="HASCoriginal.txt"
newfile="HASCnew.txt"
url="https://armedservices.house.gov/hearings"

res=$(curl "$url")

echo "$res" > "${path}/${newfile}"
newFiltered=$(sed -n '/<body id="page_hearings" class="layout_default">/I,/<\/body>/I p' "${path}/${newfile}");
echo "$newFiltered" > "${path}/${newfile}"

if cmp -s "${path}/${oldfile}" "${path}/${newfile}" ; then
   echo "Nothing changed"
else
  changed=$(diff -a "${path}/${oldfile}" "${path}/${newfile}")
  echo "${changed}"
  echo "$newFiltered" > "${path}/${oldfile}"
  comm="display notification \"New ${name} File\""
  osascript -e "${comm}"
fi
