#!/bin/bash

# Kill processes running on the ports provided 

if [ $# -eq 0 ]; then
  echo 'Must provide ports.'
  exit 1
fi

# Is variable a number?
re='^[0-9]+$'

for var in "$@"
do
  if [[ ! $var =~ $re ]]; then
    echo "ERROR: $1 is not an integer."
    continue
  fi
  PID=$(lsof -i :${var} | awk 'NR>1 {print $2}')
  if [[ -z "$PID" ]]; then
    echo "ERROR: Process not running on port ${var}"
  else
    echo $PID | xargs kill
    if [[ $? -eq 1 ]]; then
      echo "ERROR: Problem killing process on port ${var}"
    else
      echo "Process on port ${var} killed"
    fi
  fi
done;
