#!/bin/bash
mkcd () {
  mkdir "$1"
  cd "$1"
}

if [ $# -eq 0 ]; then
   echo "Must provide project name";
   exit 1;
fi

mkcd $1
git clone git@gist.github.com:0824f1ca1eba5359a950201c6bcca2cd.git .
rm -rf .git
yarn install
touch .gitignore
echo 'node_modules' > .gitignore
nvim
